# Generated by Django 4.1.4 on 2022-12-19 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='id',
        ),
        migrations.AddField(
            model_name='band',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='band',
            name='biography',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='band',
            name='medal',
            field=models.CharField(blank=True, choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], max_length=10),
        ),
        migrations.AddField(
            model_name='band',
            name='official_homepage',
            field=models.URLField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='band',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='band',
            name='year_formed',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)]),
        ),
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
