# Generated by Django 4.1.4 on 2022-12-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='id',
        ),
        migrations.AddField(
            model_name='listing',
            name='name',
            field=models.CharField(default='hello', max_length=100, primary_key=True, serialize=False),
        ),
    ]
